import type { Metadata } from "next";
import AuthContainer from "@/containers/auth";

export const metadata: Metadata = {
  title: "On The Way",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AuthContainer>{children}</AuthContainer>;
}
