import type { Metadata } from "next";
import AdminContainer from "@/containers/admin";

export const metadata: Metadata = {
  title: "On The Way",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AdminContainer>{children}</AdminContainer>;
}
